### ISSUE TITLE
Telegram version of your bot

### ISSUE THREAD

**Issue by rahulps1000** [midjourney/docs#32]
Hi Team,
I am telegram bot developer and I would like to your bot in telegram. Can you please create a telegram version or please provide the api for this and I will create the bot.
The telegram bot will have much wider audience.
Thanks and regards,
Rahul

**Comment by MvonK** [comment]
We have no plans for an API at the moment or a telegram bot, we may reconsider in the future

**Comment by rahulps1000** [comment]
Thanks for the response
I hope a telegram version is released soon

**Comment by nordskill** [comment]
I join to the idea of Telegram bot. Because Discord's desktop performance (on Windows) is very bad. Talking just about the Discord app's UI, which is not optimized for long threads.

**Comment by dreit-p** [comment]
I'm here for this too. Telegram bot will be much more useful and versatile.
