### ISSUE TITLE
Discord Invite Invalid

### ISSUE THREAD

**Issue by Streyder** [midjourney/docs#33]
Sadly your mentioned discord invite https://discord.gg/midjourney is no longer valid:

![image](https://user-images.githubusercontent.com/18559266/183388325-d7b0e5ce-830b-41b1-8d53-d5fd8ce4ab87.png)

Would be amazing if we could join you guys again!

Best
Striky

**Comment by MvonK** [comment]
Invite is still valid, please troubleshoot this with discord
