### ISSUE TITLE
Broken link pointing to Not Found URL on #rules Discord Channel

### ISSUE THREAD

**Issue by xetnos** [midjourney/docs#39]
I was casually reading the #rules channel on Discord, but found out a broken URL.
https://discord.com/channels/662267976984297473/964598182225002516/964599737275809872

You got the following:

> 12. Supplemental terms
> 
> You may choose to elect the "Beta Model" (available 8/22/2022) to create Assets on the Service. Your use of this model may be subject to license and use restrictions as explained in the Creative ML OpenRAIL-M license: https://github.com/midjourney/docs/blob/main/creative-ml-openrail-m-license.md 

That link is pointing to a broken URL

**Comment by SebbyLaw** [comment]
Fixed
