### ISSUE TITLE
Stripe doesnt accept payments from Russia

### ISSUE THREAD

**Issue by SamTyurenkov** [midjourney/docs#41]
Wanted to subscribe, but my debit card issued by russian bank is denied by Stripe.

Do you plan to add more payment options soon? E.g. payment from a phone balance or other gateway?

Also, if I meanwhile manage to subscribe with a friends card, how do I generate images in a same style? I saw in showcase a novel with images in a same style, any particular commands for that?

Thanks!

**Comment by MvonK** [comment]
No plans to support other methods of payment at the moment. For general support questions message support channels in our discord
