### ISSUE TITLE
Public API for Midjourney?

### ISSUE THREAD

**Issue by qmarsala** [midjourney/docs#42]
I was wondering if there are any plans to expose the API to Midjourney, to enable community driven clients that offer an experience outside of discord?  I'd be very interested in interacting with Midjourney more programmatically in the future.

**Comment by SebbyLaw** [comment]
There is currently no public API for Midjourney.

**Comment by qmarsala** [comment]
> There is currently no public API for Midjourney.

any plans for this in the future? or very unlikely?

**Comment by lososeg** [comment]
We want public API :) and we ready to pay

**Comment by profispojka** [comment]
Please give us the public API and I will renew my subscription.

**Comment by softyoda** [comment]
Hi, sorry to answer in this topic, I don't know where to go. I can't access the discord and all email are no-reply.

I have paid, but I can't access the server.
