### ISSUE TITLE
Update documentation to v4

### ISSUE THREAD

**Issue by apaatsio** [midjourney/docs#47]
It seems that the current documentation is for version 3. Please update it to version 4.

For example, the documentation says that `--stylize` can be "any integer between 625 and 60000". But when I try to use value 10000, the bot responds with

```
Invalid parameter
--stylize must be between 0 and 1000 with --version 4
```

**Comment by SebbyLaw** [comment]
The documentation has moved. See https://docs.midjourney.com/docs/stylize
