### ISSUE TITLE
API plans for one are in the works,Is there any timetable?

### ISSUE THREAD

**Issue by nyingping** [midjourney/docs#49]
https://github.com/midjourney/docs/blob/main/data/faq.txt#L871

![企业微信截图_16790208279091](https://user-images.githubusercontent.com/10743150/225798644-5479e336-b5ac-4abd-ad8a-4ec5f6125cc0.png)

Is there any timetable?

**Comment by SebbyLaw** [comment]
There is currently no public roadmap. It will be announced when there is one.
